load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "helpers",
    srcs = glob(["*.cpp"]),
    hdrs = glob(["*.h"]),
    deps = [

    ],
    visibility = [
        "//visibility:public"
    ]
)
