# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.24.0/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.24.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/maciejmleczko/projects/cpp/mergeLines

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/maciejmleczko/projects/cpp/mergeLines

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/opt/homebrew/Cellar/cmake/3.24.0/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.24.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.24.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/maciejmleczko/projects/cpp/mergeLines/CMakeFiles /Users/maciejmleczko/projects/cpp/mergeLines//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/maciejmleczko/projects/cpp/mergeLines/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named helpers_library

# Build rule for target.
helpers_library: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 helpers_library
.PHONY : helpers_library

# fast build rule for target.
helpers_library/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helpers_library.dir/build.make CMakeFiles/helpers_library.dir/build
.PHONY : helpers_library/fast

#=============================================================================
# Target rules for targets named serialize_library

# Build rule for target.
serialize_library: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 serialize_library
.PHONY : serialize_library

# fast build rule for target.
serialize_library/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serialize_library.dir/build.make CMakeFiles/serialize_library.dir/build
.PHONY : serialize_library/fast

#=============================================================================
# Target rules for targets named deserialize_library

# Build rule for target.
deserialize_library: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 deserialize_library
.PHONY : deserialize_library

# fast build rule for target.
deserialize_library/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/deserialize_library.dir/build.make CMakeFiles/deserialize_library.dir/build
.PHONY : deserialize_library/fast

#=============================================================================
# Target rules for targets named take_home_test

# Build rule for target.
take_home_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 take_home_test
.PHONY : take_home_test

# fast build rule for target.
take_home_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/take_home_test.dir/build.make CMakeFiles/take_home_test.dir/build
.PHONY : take_home_test/fast

#=============================================================================
# Target rules for targets named unit_tests

# Build rule for target.
unit_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit_tests
.PHONY : unit_tests

# fast build rule for target.
unit_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/build
.PHONY : unit_tests/fast

source/main.o: source/main.cpp.o
.PHONY : source/main.o

# target to build an object file
source/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/take_home_test.dir/build.make CMakeFiles/take_home_test.dir/source/main.cpp.o
.PHONY : source/main.cpp.o

source/main.i: source/main.cpp.i
.PHONY : source/main.i

# target to preprocess a source file
source/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/take_home_test.dir/build.make CMakeFiles/take_home_test.dir/source/main.cpp.i
.PHONY : source/main.cpp.i

source/main.s: source/main.cpp.s
.PHONY : source/main.s

# target to generate assembly for a file
source/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/take_home_test.dir/build.make CMakeFiles/take_home_test.dir/source/main.cpp.s
.PHONY : source/main.cpp.s

source/take_home_test/deserialize.o: source/take_home_test/deserialize.cpp.o
.PHONY : source/take_home_test/deserialize.o

# target to build an object file
source/take_home_test/deserialize.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/deserialize_library.dir/build.make CMakeFiles/deserialize_library.dir/source/take_home_test/deserialize.cpp.o
.PHONY : source/take_home_test/deserialize.cpp.o

source/take_home_test/deserialize.i: source/take_home_test/deserialize.cpp.i
.PHONY : source/take_home_test/deserialize.i

# target to preprocess a source file
source/take_home_test/deserialize.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/deserialize_library.dir/build.make CMakeFiles/deserialize_library.dir/source/take_home_test/deserialize.cpp.i
.PHONY : source/take_home_test/deserialize.cpp.i

source/take_home_test/deserialize.s: source/take_home_test/deserialize.cpp.s
.PHONY : source/take_home_test/deserialize.s

# target to generate assembly for a file
source/take_home_test/deserialize.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/deserialize_library.dir/build.make CMakeFiles/deserialize_library.dir/source/take_home_test/deserialize.cpp.s
.PHONY : source/take_home_test/deserialize.cpp.s

source/take_home_test/helpers.o: source/take_home_test/helpers.cpp.o
.PHONY : source/take_home_test/helpers.o

# target to build an object file
source/take_home_test/helpers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helpers_library.dir/build.make CMakeFiles/helpers_library.dir/source/take_home_test/helpers.cpp.o
.PHONY : source/take_home_test/helpers.cpp.o

source/take_home_test/helpers.i: source/take_home_test/helpers.cpp.i
.PHONY : source/take_home_test/helpers.i

# target to preprocess a source file
source/take_home_test/helpers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helpers_library.dir/build.make CMakeFiles/helpers_library.dir/source/take_home_test/helpers.cpp.i
.PHONY : source/take_home_test/helpers.cpp.i

source/take_home_test/helpers.s: source/take_home_test/helpers.cpp.s
.PHONY : source/take_home_test/helpers.s

# target to generate assembly for a file
source/take_home_test/helpers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helpers_library.dir/build.make CMakeFiles/helpers_library.dir/source/take_home_test/helpers.cpp.s
.PHONY : source/take_home_test/helpers.cpp.s

source/take_home_test/serialize.o: source/take_home_test/serialize.cpp.o
.PHONY : source/take_home_test/serialize.o

# target to build an object file
source/take_home_test/serialize.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serialize_library.dir/build.make CMakeFiles/serialize_library.dir/source/take_home_test/serialize.cpp.o
.PHONY : source/take_home_test/serialize.cpp.o

source/take_home_test/serialize.i: source/take_home_test/serialize.cpp.i
.PHONY : source/take_home_test/serialize.i

# target to preprocess a source file
source/take_home_test/serialize.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serialize_library.dir/build.make CMakeFiles/serialize_library.dir/source/take_home_test/serialize.cpp.i
.PHONY : source/take_home_test/serialize.cpp.i

source/take_home_test/serialize.s: source/take_home_test/serialize.cpp.s
.PHONY : source/take_home_test/serialize.s

# target to generate assembly for a file
source/take_home_test/serialize.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serialize_library.dir/build.make CMakeFiles/serialize_library.dir/source/take_home_test/serialize.cpp.s
.PHONY : source/take_home_test/serialize.cpp.s

test/tests.o: test/tests.cpp.o
.PHONY : test/tests.o

# target to build an object file
test/tests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/test/tests.cpp.o
.PHONY : test/tests.cpp.o

test/tests.i: test/tests.cpp.i
.PHONY : test/tests.i

# target to preprocess a source file
test/tests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/test/tests.cpp.i
.PHONY : test/tests.cpp.i

test/tests.s: test/tests.cpp.s
.PHONY : test/tests.s

# target to generate assembly for a file
test/tests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/test/tests.cpp.s
.PHONY : test/tests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... deserialize_library"
	@echo "... helpers_library"
	@echo "... serialize_library"
	@echo "... take_home_test"
	@echo "... unit_tests"
	@echo "... source/main.o"
	@echo "... source/main.i"
	@echo "... source/main.s"
	@echo "... source/take_home_test/deserialize.o"
	@echo "... source/take_home_test/deserialize.i"
	@echo "... source/take_home_test/deserialize.s"
	@echo "... source/take_home_test/helpers.o"
	@echo "... source/take_home_test/helpers.i"
	@echo "... source/take_home_test/helpers.s"
	@echo "... source/take_home_test/serialize.o"
	@echo "... source/take_home_test/serialize.i"
	@echo "... source/take_home_test/serialize.s"
	@echo "... test/tests.o"
	@echo "... test/tests.i"
	@echo "... test/tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

